# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '472cf612-11e8-46f7-90d6-d073311cd56e'
  containerRegistry: 'vegaabsolute.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  dockerfilePathServer: '$(Build.SourcesDirectory)/server/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Analyze_Test
  displayName: Run SonarQube and test
  jobs:
  - job: Analyze
    displayName: Analyze
    pool:
      vmImage: $(vmImageName)
    steps:
    
    - task: SonarQubePrepare@5
      inputs:
        SonarQube: 'SonarQUbe'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: '426-Gang_vega-web_AYFABbEydRFwdp6VMoPJ'
        cliProjectName: 'vega-web'
        cliSources: '.'

    - task: SonarQubeAnalyze@5
    - task: SonarQubePublish@5
      inputs:
        pollingTimeoutSec: '300'
        
- stage: BuildAndPush
  displayName: Build and push images to container repository
  jobs:
  - job: BuildandPush
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: vegaweb
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          latest
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: vegawebserver
        dockerfile: $(dockerfilePathServer)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          latest