# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master
- dev

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}: 
    dockerRegistryServiceConnection: '472cf612-11e8-46f7-90d6-d073311cd56e'
    containerRegistry: 'vegaabsolute.azurecr.io'
  ${{ else }} :
    dockerRegistryServiceConnection: '5043ee8c-6dea-4efd-b1cd-d24fa26fdc3c'
    containerRegistry: 'vegadevregistry.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'


  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Analyze
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  displayName: Run SonarQube
  jobs:
  - job: Analyze
    displayName: Analyze
    pool:
      vmImage: $(vmImageName)
    steps:
    
    - task: SonarQubePrepare@5
      inputs:
        SonarQube: 'SonarQUbe'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: '426-Gang_vega-web_AYFABbEydRFwdp6VMoPJ'
        cliProjectName: 'vega-web'
        cliSources: '.'

    - task: SonarQubeAnalyze@5
    - task: SonarQubePublish@5
      inputs:
        pollingTimeoutSec: '300'

- stage: Unit_Test
  condition: ne(variables['Build.SourceBranch'], 'refs/heads/master')
  displayName: Run unit tests
  jobs:
  - job: Test
    displayName: Test
    pool:
      vmImage: $(vmImageName)
    
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm test -- --watchAll=false
      displayName: 'Run unit tests'
        
- stage: BuildAndPush
  condition: or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.SourceBranch'], 'refs/heads/dev'))
  displayName: Build and push images to container repository
  jobs:
  - job: BuildandPush
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: 'vegaweb'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
          latest
        arguments: '--build-arg REACT_APP_WEBSERVER_URL=vega-webserver-dev.azurewebsites.net'
        
    - task: Docker@2
      displayName: push image to container registry
      inputs:
        command: push
        repository: vegaweb
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          latest
    - task: AzureRmWebAppDeployment@4
      condition: eq(variables['Build.SourceBranchName'], 'dev')
      displayName: 'Deploy Dev Frontend'
      inputs:
        azureSubscription: 'Azure for Students (63ecfa31-9ab6-4ab7-8c8d-dd55767d7a40)'
        appType: webAppContainer
        WebAppName: 'vega-web-dev'
        DockerNamespace: vegadevregistry.azurecr.io
        DockerRepository: vegaweb
        DockerImageTag: latest