version: '3'

services:
  backend:
    build:
      context: ./vega-server
      dockerfile: ./Dockerfile
    image: "venus/quantum"
    ports:
      - "8000:8000"
    environment:
      - API_URL=${MY_IP}:8080
      - FRONTEND_URL=${MY_IP}:3000
  frontend:
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        - WEBSERVER_URL=${MY_IP}:8000
    image: "venus/theswitch"
    ports:
      - "3000:3000"
